version: "3.8"

services:
  go:
    image: golang:1.21.1-alpine
    container_name: go-expirements
    command: ["sh", "-c", "apk update && apk add --no-cache bash && exec /bin/bash"]
    volumes:
      - /home/akkp/Documents/study/go/go-expirements:/go/src
    tty: true
